### ISSUE TITLE
Generic Requests

### ISSUE THREAD

**Issue by philsturgeon** [chriswoodford/foursquare-php#2]
It would be great if there was a way to make generic requests to the API, not just predefined PHP functions and responses. That way you can do ANYthing, not just whatever you've thought of.

**Comment by chriswoodford** [comment]
It's not so much what I've thought of, but more aiming to cover the entire API endpoint grid
https://developer.foursquare.com/docs/

The thing I don't like about the generic request is having to remember specific endpoints and associated parameters. Ideally (and eventually) I'll have wrapped all the endpoints behind methods whose signatures will correspond to the parameters required.

All that said, I could probably just extend the EndpointGateway to create a GenericGateway. I guess that would be the most encompassing since people could choose their preferred of accessing the data. Everybody wins? 

I'll add it to my dev queue

**Comment by philsturgeon** [comment]
Exactly right, it does not need to be a proposed solution, but having it there won't make kittens sad.

I need to add a few endpoints myself, as venue search is incomplete. Expect a PR on Monday.

**Comment by chriswoodford** [comment]
Generic requests are now possible through the EndpointGateway using the methods EndpointGateway::makeApiRequest (for unauthenticated requests) and EndpointGateway::makeAuthenticatedApiRequest (for authenticated requests).

https://github.com/chriswoodford/foursquare-php/blob/75244be708b487c81bc5961718f87841db20f3e8/lib/TheTwelve/Foursquare/EndpointGateway.php

You can get an instance of the EndpointGateway via a call to ApiGatewayFactory::getGenericGateway
